export enum USER_ACTION_TYPE {
  TOGGLE_HERO_CONTAINER = 'TOGGLE_HERO_CONTAINER',
  CLOSE_ERROR_ALERT = 'CLOSE_ERROR_ALERT',
  UPDATE_STATE = 'UPDATE_STATE',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  FIND_HOME = 'FIND_HOME',
  FIND_HOME_SUCCESS = 'FIND_HOME_SUCCESS',
  FIND_HOME_ERROR = 'FIND_HOME_ERROR',
  FIND_DROPBOX = 'FIND_DROPBOX',
  FIND_DROPBOX_SUCCESS = 'FIND_DROPBOX_SUCCESS',
  FIND_DROPBOX_ERROR = 'FIND_DROPBOX_ERROR',
}
